# Generated by Django 4.2.1 on 2024-01-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
